branch-defaults:
  default:
    environment: udagram-solomon-dev1-dev
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-solomon-dev1
  branch: null
  default_ec2_keyname: udagram-yaki-key-pair
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: yakob-2
  repository: null
  sc: null
  workspace_type: Application
